// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCldvS_eE9Pi2KzL9g88iUAKuIBEyUR6ic',
    appId: '1:128865352924:web:dcba22e6140a2867304819',
    messagingSenderId: '128865352924',
    projectId: 'blacklion-83bd5',
    authDomain: 'blacklion-83bd5.firebaseapp.com',
    storageBucket: 'blacklion-83bd5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF8lg6ulfJ7Fz10jp_2lWVB_Hz-rZZcpA',
    appId: '1:128865352924:android:177fbdee1a9e3f17304819',
    messagingSenderId: '128865352924',
    projectId: 'blacklion-83bd5',
    storageBucket: 'blacklion-83bd5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgMYq6QRCw3-aE47xm_3ORqv02xwcFHMI',
    appId: '1:128865352924:ios:37dec4a1b0a6a065304819',
    messagingSenderId: '128865352924',
    projectId: 'blacklion-83bd5',
    storageBucket: 'blacklion-83bd5.appspot.com',
    androidClientId: '128865352924-3fgkiub91lpgp1q18ou764ohu4njrsp1.apps.googleusercontent.com',
    iosClientId: '128865352924-jvat0sgiucrvlu57ibd45k6bk3p26vrv.apps.googleusercontent.com',
    iosBundleId: 'com.demakk.blackLion2023',
  );
}
